services:
  - type: web
    name: whisper-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT whisper_test:app
    envVars:
      - key: FLASK_APP
        value: whisper_test.py
      - key: WHISPER_MODEL
        value: base
