services:
  - type: web
    name: whisper-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \
      pip install -r requirements.txt
    startCommand: |
      gunicorn --workers 1 --threads 1 --timeout 120 --bind 0.0.0.0:$PORT whisper_test:app
    envVars:
      - key: WHISPER_MODEL
        value: tiny
      - key: PORT
        value: 10000
