services:
  - type: web
    name: whisper-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \  # Needed for audio processing
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm whisper_test:app
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_APP
        value: whisper_test.py
      - key: WHISPER_MODEL
        value: base  # Use "tiny" or "small" if you get memory errors